# Generated by Django 6.1.1 on 2026-09-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FleetCard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/', verbose_name='Imagem do veículo'),
        ),
    ]
